packages:
  - api-client
  - backend
  - comm
  - jupyter
  - conat
  - project
  - sync
  - sync-fs
  - sync-client
  - util
  - terminal
  - compute
  - conat

onlyBuiltDependencies:
  - '@cocalc/fuse-native'
  - websocket-sftp
  - websocketfs

